import 'dart:math';
import 'package:flutter/material.dart';

class LifeCounterPage extends StatefulWidget { const LifeCounterPage({super.key}); @override State<LifeCounterPage> createState()=>_LifeCounterPageState(); }
class _LifeCounterPageState extends State<LifeCounterPage>{
 int _count=4,_start=40; late List<_P> _p;
 @override void initState(){super.initState();_reset();}
 void _reset(){_p=List.generate(_count,(i)=>_P('Jogador ${i+1}',_start));}
 void _players(int n)=>setState((){_count=n;_reset();});
 void _life(int i,int d)=>setState(()=>_p[i].life+=d);
 void _poison(int i,int d)=>setState(()=>_p[i].poison=max(0,_p[i].poison+d));
 void _tax(int i,int d)=>setState(()=>_p[i].tax=max(0,_p[i].tax+d));
 @override Widget build(BuildContext context)=>Scaffold(appBar:AppBar(title:const Text('Mesa de jogo'),actions:[IconButton(tooltip:'Reiniciar',onPressed:_confirmReset,icon:const Icon(Icons.restart_alt_rounded))]),body:Column(children:[Padding(padding:const EdgeInsets.all(12),child:Row(children:[Expanded(child:DropdownButtonFormField<int>(initialValue:_count,decoration:const InputDecoration(labelText:'Jogadores'),items:List.generate(7,(i)=>i+2).map((n)=>DropdownMenuItem(value:n,child:Text('$n jogadores'))).toList(),onChanged:(v){if(v!=null)_players(v);})),const SizedBox(width:8),Expanded(child:DropdownButtonFormField<int>(initialValue:_start,decoration:const InputDecoration(labelText:'Vida inicial'),items:const[20,25,30,40].map((n)=>DropdownMenuItem(value:n,child:Text('$n vidas'))).toList(),onChanged:(v){if(v!=null)setState((){_start=v;_reset();});}))])),Expanded(child:LayoutBuilder(builder:(context,c){final landscape=c.maxWidth>c.maxHeight;final cols=_count<=2?1:landscape?min(4,_count):2;return GridView.builder(padding:const EdgeInsets.fromLTRB(8,0,8,12),gridDelegate:SliverGridDelegateWithFixedCrossAxisCount(crossAxisCount:cols,crossAxisSpacing:8,mainAxisSpacing:8,childAspectRatio:landscape?1.2:0.8),itemCount:_count,itemBuilder:(context,i)=>_tile(i));}))]));
 Widget _tile(int i){final p=_p[i],t=Theme.of(context),lethal=p.life<=0||p.poison>=10;return Card(clipBehavior:Clip.antiAlias,child:Container(decoration:BoxDecoration(border:lethal?Border.all(color:t.colorScheme.error,width:3):null),child:Column(children:[ListTile(dense:true,title:Text(p.name,overflow:TextOverflow.ellipsis,style:const TextStyle(fontWeight:FontWeight.w800)),trailing:IconButton(tooltip:'Editar nome',onPressed:()=>_rename(i),icon:const Icon(Icons.edit_rounded,size:18))),Expanded(child:Row(children:[Expanded(child:InkWell(onTap:()=>_life(i,-1),onLongPress:()=>_life(i,-5),child:const Center(child:Icon(Icons.remove_rounded,size:38)))),Expanded(flex:2,child:FittedBox(fit:BoxFit.scaleDown,child:Text('${p.life}',style:TextStyle(fontSize:72,fontWeight:FontWeight.w900,color:lethal?t.colorScheme.error:null)))),Expanded(child:InkWell(onTap:()=>_life(i,1),onLongPress:()=>_life(i,5),child:const Center(child:Icon(Icons.add_rounded,size:38))))])),Padding(padding:const EdgeInsets.only(bottom:8),child:Wrap(spacing:6,alignment:WrapAlignment.center,children:[ActionChip(label:Text('☠ ${p.poison}'),tooltip:'Toque +1 • segure -1',onPressed:()=>_poison(i,1),onLongPress:()=>_poison(i,-1)),ActionChip(label:Text('Tax ${p.tax}'),tooltip:'Toque +1 • segure -1',onPressed:()=>_tax(i,1),onLongPress:()=>_tax(i,-1))]))])));}
 Future<void> _rename(int i)async{final c=TextEditingController(text:_p[i].name);final v=await showDialog<String>(context:context,builder:(context)=>AlertDialog(title:const Text('Nome do jogador'),content:TextField(controller:c,autofocus:true,maxLength:18),actions:[TextButton(onPressed:()=>Navigator.pop(context),child:const Text('Cancelar')),FilledButton(onPressed:()=>Navigator.pop(context,c.text),child:const Text('Salvar'))]));c.dispose();if(v!=null&&v.trim().isNotEmpty&&mounted)setState(()=>_p[i].name=v.trim());}
 Future<void> _confirmReset()async{final ok=await showDialog<bool>(context:context,builder:(context)=>AlertDialog(title:const Text('Reiniciar partida?'),content:Text('Todos voltarão para $_start vidas, sem poison e sem Commander Tax.'),actions:[TextButton(onPressed:()=>Navigator.pop(context,false),child:const Text('Cancelar')),FilledButton(onPressed:()=>Navigator.pop(context,true),child:const Text('Reiniciar'))]))??false;if(ok&&mounted)setState(_reset);}
}
class _P{_P(this.name,this.life);String name;int life,poison=0,tax=0;}
