import 'dart:async';
import 'dart:math';
import 'package:flutter/material.dart';

class LifeCounterPage extends StatefulWidget { const LifeCounterPage({super.key}); @override State<LifeCounterPage> createState()=>_LifeCounterPageState(); }
class _LifeCounterPageState extends State<LifeCounterPage>{
 int _count=4,_start=40,_seconds=0; late List<_P> _p; int? _monarch,_initiative; final List<_Undo> _history=[]; Timer? _timer; bool _running=false,_compactSetup=false;
 @override void initState(){super.initState();_reset();}
 @override void dispose(){_timer?.cancel();super.dispose();}
 void _reset(){_p=List.generate(_count,(i)=>_P('Jogador ${i+1}',_start,_count));_monarch=null;_initiative=null;_history.clear();_seconds=0;_running=false;_timer?.cancel();}
 void _players(int n)=>setState((){_count=n;_reset();});
 void _save(int i)=>_history.add(_Undo(i,_p[i].copy(),_monarch,_initiative));
 void _life(int i,int d)=>setState((){_save(i);_p[i].life+=d;});
 void _poison(int i,int d)=>setState((){_save(i);_p[i].poison=max(0,_p[i].poison+d);});
 void _tax(int i,int d)=>setState((){_save(i);_p[i].tax=max(0,_p[i].tax+d);});
 void _cmd(int victim,int source,int d)=>setState((){_save(victim);final old=_p[victim].commander[source];final next=max(0,old+d);_p[victim].commander[source]=next;_p[victim].life-=next-old;});
 void _undo(){if(_history.isEmpty)return;setState((){final u=_history.removeLast();_p[u.index]=u.player;_monarch=u.monarch;_initiative=u.initiative;});}
 void _toggleTimer(){setState(()=>_running=!_running);_timer?.cancel();if(_running){_timer=Timer.periodic(const Duration(seconds:1),(_){if(mounted)setState(()=>_seconds++);});}}
 String get _clock=>'${(_seconds~/60).toString().padLeft(2,'0')}:${(_seconds%60).toString().padLeft(2,'0')}';
 @override Widget build(BuildContext context){final t=Theme.of(context);return Scaffold(appBar:AppBar(title:Row(children:[const Text('Mesa Commander'),const SizedBox(width:10),InkWell(borderRadius:BorderRadius.circular(18),onTap:_toggleTimer,child:Padding(padding:const EdgeInsets.symmetric(horizontal:9,vertical:5),child:Row(children:[Icon(_running?Icons.pause_rounded:Icons.play_arrow_rounded,size:17),const SizedBox(width:4),Text(_clock,style:const TextStyle(fontWeight:FontWeight.w800,fontFeatures:[]))])))]),actions:[IconButton(tooltip:_compactSetup?'Mostrar configuração':'Modo mesa',onPressed:()=>setState(()=>_compactSetup=!_compactSetup),icon:Icon(_compactSetup?Icons.tune_rounded:Icons.fullscreen_rounded)),IconButton(tooltip:'Desfazer',onPressed:_history.isEmpty?null:_undo,icon:const Icon(Icons.undo_rounded)),IconButton(tooltip:'Ferramentas',onPressed:_tools,icon:const Icon(Icons.casino_rounded))]),body:Column(children:[
 if(!_compactSetup) Padding(padding:const EdgeInsets.fromLTRB(12,8,12,6),child:Row(children:[Expanded(child:DropdownButtonFormField<int>(initialValue:_count,decoration:const InputDecoration(labelText:'Jogadores',isDense:true),items:List.generate(7,(i)=>i+2).map((n)=>DropdownMenuItem(value:n,child:Text('$n jogadores'))).toList(),onChanged:(v){if(v!=null)_players(v);})),const SizedBox(width:8),Expanded(child:DropdownButtonFormField<int>(initialValue:_start,decoration:const InputDecoration(labelText:'Vida inicial',isDense:true),items:const[20,25,30,40].map((n)=>DropdownMenuItem(value:n,child:Text('$n vidas'))).toList(),onChanged:(v){if(v!=null)setState((){_start=v;_reset();});}))])),
 if(_monarch!=null||_initiative!=null) Padding(padding:const EdgeInsets.fromLTRB(12,2,12,7),child:Wrap(spacing:8,children:[if(_monarch!=null)Chip(avatar:const Text('👑'),label:Text('Monarca: ${_p[_monarch!].name}')),if(_initiative!=null)Chip(avatar:const Icon(Icons.explore_rounded,size:17),label:Text('Iniciativa: ${_p[_initiative!].name}'))])),
 Expanded(child:LayoutBuilder(builder:(context,c){final landscape=c.maxWidth>c.maxHeight;final cols=_count<=2?1:landscape?min(4,_count):2;final ratio=landscape?(_compactSetup?1.45:1.18):(_compactSetup?.88:.76);return GridView.builder(padding:const EdgeInsets.fromLTRB(8,0,8,10),gridDelegate:SliverGridDelegateWithFixedCrossAxisCount(crossAxisCount:cols,crossAxisSpacing:8,mainAxisSpacing:8,childAspectRatio:ratio),itemCount:_count,itemBuilder:(context,i)=>_tile(i,t));}))]));}
 Widget _tile(int i,ThemeData t){final p=_p[i],cmdMax=p.commander.isEmpty?0:p.commander.reduce(max),lethal=p.life<=0||p.poison>=10||cmdMax>=21;final accent=[t.colorScheme.primary,t.colorScheme.tertiary,t.colorScheme.secondary,t.colorScheme.error][i%4];return Card(clipBehavior:Clip.antiAlias,elevation:lethal?4:1,child:Container(decoration:BoxDecoration(border:Border(top:BorderSide(color:lethal?t.colorScheme.error:accent,width:5))),child:Column(children:[Padding(padding:const EdgeInsets.fromLTRB(10,7,6,0),child:Row(children:[Expanded(child:InkWell(onTap:()=>_rename(i),child:Text(p.name,overflow:TextOverflow.ellipsis,style:const TextStyle(fontWeight:FontWeight.w900)))),if(_monarch==i)const Text('👑 '),if(_initiative==i)Icon(Icons.explore_rounded,size:17,color:accent),PopupMenuButton<String>(padding:EdgeInsets.zero,iconSize:20,onSelected:(v)=>_playerMenu(i,v),itemBuilder:(_)=>const[PopupMenuItem(value:'cmd',child:Text('Commander Damage')),PopupMenuItem(value:'monarch',child:Text('Tornar Monarca')),PopupMenuItem(value:'initiative',child:Text('Dar Iniciativa')),PopupMenuItem(value:'rename',child:Text('Editar nome'))])])),Expanded(child:Row(children:[Expanded(child:InkWell(onTap:()=>_life(i,-1),onLongPress:()=>_life(i,-5),child:Center(child:Icon(Icons.remove_rounded,size:42,color:accent)))),Expanded(flex:2,child:FittedBox(fit:BoxFit.scaleDown,child:Text('${p.life}',style:TextStyle(fontSize:88,fontWeight:FontWeight.w900,height:.9,color:lethal?t.colorScheme.error:null)))),Expanded(child:InkWell(onTap:()=>_life(i,1),onLongPress:()=>_life(i,5),child:Center(child:Icon(Icons.add_rounded,size:42,color:accent))))])),Padding(padding:const EdgeInsets.fromLTRB(7,0,7,7),child:Wrap(spacing:5,runSpacing:3,alignment:WrapAlignment.center,children:[ActionChip(label:Text('☠ ${p.poison}'),tooltip:'Poison: toque +1 • segure -1',onPressed:()=>_poison(i,1),onLongPress:()=>_poison(i,-1)),ActionChip(label:Text('Tax ${p.tax}'),tooltip:'Commander Tax: toque +1 • segure -1',onPressed:()=>_tax(i,1),onLongPress:()=>_tax(i,-1)),ActionChip(avatar:const Icon(Icons.shield_outlined,size:15),label:Text(cmdMax>0?'CMD $cmdMax/21':'CMD'),onPressed:()=>_commanderSheet(i))]))])));}
 void _playerMenu(int i,String v){if(v=='cmd')_commanderSheet(i);if(v=='rename')_rename(i);if(v=='monarch')setState(()=>_monarch=_monarch==i?null:i);if(v=='initiative')setState(()=>_initiative=_initiative==i?null:i);}
 Future<void> _commanderSheet(int victim)async{await showModalBottomSheet(context:context,isScrollControlled:true,builder:(context)=>SafeArea(child:Padding(padding:const EdgeInsets.all(18),child:Column(mainAxisSize:MainAxisSize.min,crossAxisAlignment:CrossAxisAlignment.start,children:[Text('Commander Damage em ${_p[victim].name}',style:Theme.of(context).textTheme.titleLarge?.copyWith(fontWeight:FontWeight.w900)),const SizedBox(height:4),Text('O dano reduz a vida automaticamente. 21 do mesmo comandante é letal.',style:TextStyle(color:Theme.of(context).colorScheme.onSurfaceVariant)),const SizedBox(height:14),...List.generate(_count,(source){if(source==victim)return const SizedBox.shrink();final value=_p[victim].commander[source];return ListTile(contentPadding:EdgeInsets.zero,title:Text(_p[source].name,style:const TextStyle(fontWeight:FontWeight.w700)),subtitle:LinearProgressIndicator(value:min(1,value/21)),leading:CircleAvatar(child:Text('${source+1}')),trailing:Row(mainAxisSize:MainAxisSize.min,children:[IconButton(onPressed:(){_cmd(victim,source,-1);Navigator.pop(context);_commanderSheet(victim);},icon:const Icon(Icons.remove_circle_outline_rounded)),SizedBox(width:48,child:Text('$value/21',textAlign:TextAlign.center,style:const TextStyle(fontWeight:FontWeight.w900))),IconButton(onPressed:(){_cmd(victim,source,1);Navigator.pop(context);_commanderSheet(victim);},icon:const Icon(Icons.add_circle_outline_rounded))]));})]))));}
 Future<void> _tools()async{await showModalBottomSheet(context:context,builder:(context)=>SafeArea(child:Padding(padding:const EdgeInsets.all(18),child:Column(mainAxisSize:MainAxisSize.min,children:[Text('Ferramentas da mesa',style:Theme.of(context).textTheme.titleLarge?.copyWith(fontWeight:FontWeight.w900)),const SizedBox(height:8),ListTile(leading:Icon(_running?Icons.pause_circle:Icons.play_circle),title:Text(_running?'Pausar cronômetro':'Iniciar cronômetro'),subtitle:Text('Tempo da partida: $_clock'),onTap:(){Navigator.pop(context);_toggleTimer();}),ListTile(leading:const Icon(Icons.casino_rounded),title:const Text('Rolar D20'),onTap:(){final n=Random().nextInt(20)+1;Navigator.pop(context);ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text('🎲 D20: $n')));}),ListTile(leading:const Icon(Icons.paid_rounded),title:const Text('Cara ou coroa'),onTap:(){final v=Random().nextBool()?'Cara':'Coroa';Navigator.pop(context);ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text('🪙 $v')));}),ListTile(leading:const Icon(Icons.undo_rounded),title:const Text('Desfazer última alteração'),enabled:_history.isNotEmpty,onTap:(){Navigator.pop(context);_undo();}),ListTile(leading:const Icon(Icons.restart_alt_rounded),title:const Text('Nova partida'),onTap:(){Navigator.pop(context);_confirmReset();})]))));}
 Future<void> _rename(int i)async{final c=TextEditingController(text:_p[i].name);final v=await showDialog<String>(context:context,builder:(context)=>AlertDialog(title:const Text('Nome do jogador'),content:TextField(controller:c,autofocus:true,maxLength:18),actions:[TextButton(onPressed:()=>Navigator.pop(context),child:const Text('Cancelar')),FilledButton(onPressed:()=>Navigator.pop(context,c.text),child:const Text('Salvar'))]));c.dispose();if(v!=null&&v.trim().isNotEmpty&&mounted)setState(()=>_p[i].name=v.trim());}
 Future<void> _confirmReset()async{final ok=await showDialog<bool>(context:context,builder:(context)=>AlertDialog(title:const Text('Nova partida?'),content:Text('Todos voltarão para $_start vidas. Poison, Commander Damage, Tax, Monarca, Iniciativa e cronômetro serão zerados.'),actions:[TextButton(onPressed:()=>Navigator.pop(context,false),child:const Text('Cancelar')),FilledButton(onPressed:()=>Navigator.pop(context,true),child:const Text('Reiniciar'))]))??false;if(ok&&mounted)setState(_reset);}
}
class _P{_P(this.name,this.life,int count):commander=List.filled(count,0);String name;int life,poison=0,tax=0;List<int> commander;_P copy(){final p=_P(name,life,commander.length)..poison=poison..tax=tax;p.commander=List.of(commander);return p;}}
class _Undo{_Undo(this.index,this.player,this.monarch,this.initiative);final int index;final _P player;final int? monarch,initiative;}
